version: 2
updates:
  - package-ecosystem: npm
    directory: /desktop
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Asuncion
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: America/Asuncion
    open-pull-requests-limit: 5
