'use strict';
const $=id=>document.getElementById(id);
const views=[...document.querySelectorAll('[data-view-panel]')];
const sideLinks=[...document.querySelectorAll('[data-view]')];
const LOCAL_PROJECTS_KEY='happyCoding.projects.v1',BOOKMARKS_KEY='happyCoding.bookmarks.v1',HISTORY_KEY='happyCoding.history.v1',STREAK_KEY='happyCoding.streak.v1';
const baseProjects=[
{id:'soulbound',name:'Soulbound',engine:'Godot 4 · GDScript',short:'Godot',icon:'G',description:'RPG narrativo',edited:'última edição há 18 min',version:'v0.7.2'},
{id:'pixel-forge',name:'Pixel Forge',engine:'Phaser · TypeScript',short:'Web',icon:'JS',description:'Game jam',edited:'última edição ontem',version:'v0.4.0'},
{id:'quiet-forest',name:'Quiet Forest',engine:'Unity · C#',short:'Unity',icon:'U',description:'Experimento atmosférico',edited:'projeto recente',version:'v0.2.1'}
];
let warningUrl=null,focusSeconds=1500,focusTimer=null;
const readJson=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const writeJson=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const getProjects=()=>[...baseProjects,...readJson(LOCAL_PROJECTS_KEY,[])];
const getBookmarks=()=>readJson(BOOKMARKS_KEY,[]),getHistory=()=>readJson(HISTORY_KEY,[]);
function toast(message){const t=$('toast');t.textContent=message;t.classList.remove('hidden');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.add('hidden'),2200)}
function showView(name){views.forEach(v=>v.classList.toggle('active',v.dataset.viewPanel===name));sideLinks.forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('menuPanel').classList.add('hidden');if(name==='projects')renderProjects();if(name==='settings')updateSettingsCounts();window.scrollTo({top:0,behavior:'smooth'})}
sideLinks.forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
document.querySelectorAll('[data-view-jump]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.viewJump)));
function projectCard(p){return `<article class="project-card"><div class="project-top"><span class="project-symbol">${escapeHtml(p.icon||'•')}</span><span class="project-menu">•••</span></div><span class="tech-pill">${escapeHtml(String(p.engine).toUpperCase())}</span><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.description||'Novo projeto')} · ${escapeHtml(p.edited||'salvo neste navegador')}</p><footer><span>${escapeHtml(p.version||'local')}</span><button data-open-project="${escapeHtml(p.id)}">Abrir projeto →</button></footer></article>`}
function renderProjects(){const projects=getProjects();const homeCards=projects.slice(0,2).map(projectCard).join('')+`<article class="project-card new-project-card" id="newProjectCard"><div class="new-project-plus">+</div><h3>Começar algo novo</h3><p>Crie um espaço para seu próximo jogo, site ou experimento.</p><footer><span></span><button type="button">Novo projeto</button></footer></article>`;$('projectGrid').innerHTML=homeCards;$('allProjects').innerHTML=projects.map(projectCard).join('');$('projectCount').textContent=String(projects.length);$('recentProjects').innerHTML=projects.slice(0,3).map(p=>`<button data-project-shortcut="${escapeHtml(p.id)}">${escapeHtml(p.name)} <span>${escapeHtml(p.short||String(p.engine).split('·')[0].trim())}</span></button>`).join('');document.querySelectorAll('[data-open-project],[data-project-shortcut]').forEach(btn=>btn.addEventListener('click',()=>toast('Editor de projetos entra na próxima etapa =]')));const np=$('newProjectCard');if(np)np.addEventListener('click',()=>$('projectModal').classList.remove('hidden'))}
$('newProjectBtn').addEventListener('click',()=>$('projectModal').classList.remove('hidden'));
$('projectForm').addEventListener('submit',e=>{e.preventDefault();const items=readJson(LOCAL_PROJECTS_KEY,[]);items.unshift({id:crypto.randomUUID?.()||String(Date.now()),name:$('projectName').value.trim(),engine:$('projectEngine').value,short:'Local',icon:'+',description:$('projectDescription').value.trim(),edited:'salvo neste navegador',version:'local'});writeJson(LOCAL_PROJECTS_KEY,items);$('projectForm').reset();$('projectModal').classList.add('hidden');renderProjects();toast('Projeto criado neste navegador.')});
document.querySelectorAll('[data-close-modal]').forEach(btn=>btn.addEventListener('click',()=>$(btn.dataset.closeModal).classList.add('hidden')));
function isAdultQuery(q){const t=q.toLowerCase();return ['porn','porno','pornografia','hentai','xvideos','xnxx','onlyfans nude','nudes','sexo explícito','sex videos','rule34','nhentai'].some(x=>t.includes(x))}
function needsContentWarning(url){const s=url.toLowerCase();return ['horror','terror','gore-game','violent-game','mature-game'].some(x=>s.includes(x))}
function normalizeTarget(raw){const v=raw.trim();if(!v||v==='happy://home')return{kind:'home'};if(isAdultQuery(v))return{kind:'blocked'};if(/^https?:\/\//i.test(v))return{kind:'url',url:v};if(/^([a-z0-9-]+\.)+[a-z]{2,}(\/.*)?$/i.test(v))return{kind:'url',url:'https://'+v};return{kind:'url',url:'https://www.google.com/search?safe=active&q='+encodeURIComponent(v)}}
function addHistory(url){const h=getHistory();h.unshift({url,at:new Date().toISOString()});writeJson(HISTORY_KEY,h.slice(0,100))}
function navigate(raw){const t=normalizeTarget(raw);if(t.kind==='home'){showView('home');$('addressInput').value='happy://home';return}if(t.kind==='blocked'){$('blockedModal').classList.remove('hidden');return}if(needsContentWarning(t.url)){warningUrl=t.url;$('warningModal').classList.remove('hidden');return}addHistory(t.url);window.open(t.url,'_blank','noopener');$('addressInput').value=t.url}
$('addressForm').addEventListener('submit',e=>{e.preventDefault();navigate($('addressInput').value)});$('universalSearch').addEventListener('submit',e=>{e.preventDefault();navigate($('searchInput').value)});$('homeBtn').addEventListener('click',()=>navigate('happy://home'));$('reloadBtn').addEventListener('click',()=>location.reload());$('backBtn').addEventListener('click',()=>history.back());$('forwardBtn').addEventListener('click',()=>history.forward());$('newTabBtn').addEventListener('click',()=>{showView('home');$('addressInput').value='happy://home';toast('Nova aba — no app desktop ela será uma aba real.')});
$('bookmarkBtn').addEventListener('click',()=>{const url=$('addressInput').value||'happy://home',list=getBookmarks();if(!list.some(i=>i.url===url)){list.unshift({url,title:url==='happy://home'?'Happy Coding =]':url});writeJson(BOOKMARKS_KEY,list)}updateSettingsCounts()});
function updateSettingsCounts(){const n=getBookmarks().length;$('bookmarkCount').textContent=`${n} salvo${n===1?'':'s'}`;$('menuBookmarkCount').textContent=String(n)}
$('clearHistory').addEventListener('click',()=>{writeJson(HISTORY_KEY,[]);toast('Histórico local apagado.')});$('menuBtn').addEventListener('click',()=>$('menuPanel').classList.toggle('hidden'));$('closeMenu').addEventListener('click',()=>$('menuPanel').classList.add('hidden'));$('menuBookmarks').addEventListener('click',()=>{const list=getBookmarks();if(!list.length)return toast('Nenhum favorito ainda.');const c=prompt('Favoritos:\n\n'+list.map((x,i)=>`${i+1}. ${x.title}`).join('\n')+'\n\nDigite o número para abrir:');const i=Number(c)-1;if(list[i])navigate(list[i].url)});$('menuHistory').addEventListener('click',()=>{const l=getHistory();if(!l.length)return toast('Histórico local vazio.');alert('Histórico local recente:\n\n'+l.slice(0,10).map(x=>x.url).join('\n'))});
$('warningCancel').addEventListener('click',()=>{warningUrl=null;$('warningModal').classList.add('hidden')});$('warningContinue').addEventListener('click',()=>{const u=warningUrl;warningUrl=null;$('warningModal').classList.add('hidden');if(u){addHistory(u);window.open(u,'_blank','noopener')}});document.querySelectorAll('[data-external]').forEach(btn=>btn.addEventListener('click',()=>navigate(btn.dataset.external)));document.querySelectorAll('[data-tool]').forEach(btn=>btn.addEventListener('click',()=>showView('tools')));
$('formatJson').addEventListener('click',()=>{try{$('jsonInput').value=JSON.stringify(JSON.parse($('jsonInput').value),null,2);$('jsonStatus').textContent='JSON válido ✓'}catch{$('jsonStatus').textContent='JSON inválido'}});$('colorPicker').addEventListener('input',e=>{const v=e.target.value.toUpperCase();$('colorPreview').style.background=v;$('colorValue').textContent=v});$('testRegex').addEventListener('click',()=>{try{const re=new RegExp($('regexPattern').value,'gi'),m=$('regexText').value.match(re)||[];$('regexStatus').textContent=`${m.length} correspondência(s)`}catch{$('regexStatus').textContent='Expressão inválida'}});
function renderClock(){const m=String(Math.floor(focusSeconds/60)).padStart(2,'0'),s=String(focusSeconds%60).padStart(2,'0');$('focusClock').textContent=`${m}:${s}`}
$('focusStart').addEventListener('click',()=>{if(focusTimer){clearInterval(focusTimer);focusTimer=null;$('focusStart').textContent='Iniciar';return}$('focusStart').textContent='Pausar';focusTimer=setInterval(()=>{if(focusSeconds>0){focusSeconds--;renderClock()}else{clearInterval(focusTimer);focusTimer=null;$('focusStart').textContent='Iniciar';toast('Focus run concluído! =]')}},1000)});$('focusReset').addEventListener('click',()=>{if(focusTimer)clearInterval(focusTimer);focusTimer=null;focusSeconds=1500;renderClock();$('focusStart').textContent='Iniciar'});
$('mascotBtn').addEventListener('click',()=>$('mascotPanel').classList.toggle('hidden'));$('closeMascot').addEventListener('click',()=>$('mascotPanel').classList.add('hidden'));$('chatForm').addEventListener('submit',e=>{e.preventDefault();const i=$('chatInput'),text=i.value.trim();if(!text)return;$('chatLog').insertAdjacentHTML('beforeend',`<p class="user">${escapeHtml(text)}</p>`);i.value='';const replies=['Pronto pra criar algo incrível? =]','Boa ideia =]','Se der erro, manda a mensagem pra mim.','Ainda sou o mascote com falas prontas; a IA real vem depois.'];setTimeout(()=>{$('chatLog').insertAdjacentHTML('beforeend',`<p class="bot">${replies[Math.floor(Math.random()*replies.length)]}</p>`);$('chatLog').scrollTop=$('chatLog').scrollHeight},220)});$('feedbackBtn').addEventListener('click',()=>toast('Feedback entra numa próxima versão.'));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('searchInput').focus()}});
function setupGreeting(){const h=new Date().getHours();$('greeting').textContent=h<12?'Bom dia':h<18?'Boa tarde':'Boa noite';const stored=readJson(STREAK_KEY,null),today=new Date().toISOString().slice(0,10);let days=12;if(!stored)writeJson(STREAK_KEY,{last:today,days});else{days=stored.days||12;if(stored.last!==today){const diff=(new Date(today)-new Date(stored.last))/86400000;days=diff===1?days+1:diff>1?1:days;writeJson(STREAK_KEY,{last:today,days})}}$('streakDays').textContent=String(days)}
setupGreeting();renderProjects();renderClock();updateSettingsCounts();