'use strict';
// Fixed isolated-world scripts: no Node, preload bridge or arbitrary code from the UI.
const AUDIT=`(()=>{const issues=[];const push=(kind,el,message)=>{if(issues.length>=80)return;issues.push({kind,tag:el.tagName,selector:el.id?'#'+CSS.escape(el.id):el.tagName.toLowerCase(),message,x:Math.round(el.getBoundingClientRect().x),y:Math.round(el.getBoundingClientRect().y)});};for(const el of [...document.querySelectorAll('img,input,select,textarea,button,a')].slice(0,3000)){const r=el.getBoundingClientRect();if(!r.width||!r.height)continue;if(r.right>innerWidth+2)push('layout',el,'Elemento ultrapassa a largura da tela.');if(el.tagName==='IMG'){if(!el.hasAttribute('alt'))push('acessibilidade',el,'Imagem sem atributo alt.');if(el.complete&&el.naturalWidth===0)push('recurso',el,'Imagem não carregou.');}if(['INPUT','SELECT','TEXTAREA'].includes(el.tagName)&&el.type!=='hidden'&&!el.labels?.length&&!el.getAttribute('aria-label')&&!el.getAttribute('aria-labelledby')&&!['submit','button'].includes(el.type))push('acessibilidade',el,'Campo sem rótulo acessível.');if(['BUTTON','A'].includes(el.tagName)&&!(el.innerText||el.getAttribute('aria-label')||el.querySelector('img[alt]')?.alt||'').trim())push('acessibilidade',el,'Controle sem nome acessível.');}const lum=c=>c.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((sum,v,i)=>sum+v*[.2126,.7152,.0722][i],0);const rgb=c=>{const m=c.match(/^rgb\\((\\d+), (\\d+), (\\d+)\\)$/);return m?m.slice(1).map(Number):null;};for(const el of [...document.querySelectorAll('p,span,a,button,label,h1,h2,h3')].slice(0,1000)){if(!el.textContent.trim()||!el.getBoundingClientRect().width)continue;const st=getComputedStyle(el),fg=rgb(st.color);let bg=null,node=el,complex=false;while(node&&!bg){const style=getComputedStyle(node);if(style.backgroundImage!=='none'||Number(style.opacity)<1){complex=true;break;}bg=rgb(style.backgroundColor);node=node.parentElement;}if(complex||!fg||!bg)continue;const a=lum(fg),b=lum(bg),ratio=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);const large=parseFloat(st.fontSize)>=24||(parseFloat(st.fontSize)>=18.66&&parseInt(st.fontWeight)>=700);if(ratio<(large?3:4.5))push('contraste',el,'Contraste estimado '+ratio.toFixed(2)+':1 em fundo sólido. Confira no DevTools.');}return {issues,width:innerWidth,height:innerHeight,title:document.title};})()`;
const RECORD_START=`(()=>{if(globalThis.__hcRecorder)globalThis.__hcRecorder.stop();const q=[];function selector(el){if(el.id)return '#'+CSS.escape(el.id);const parts=[];while(el&&el!==document.documentElement&&parts.length<6){const parent=el.parentElement;if(!parent)break;parts.unshift(el.tagName.toLowerCase()+':nth-child('+([...parent.children].indexOf(el)+1)+')');el=parent;}return parts.join(' > ');}const handler=e=>{if(!e.isTrusted||q.length>=30)return;const el=e.target.closest('button,a,[role=button]');if(!el)return;q.push({type:'click',selector:selector(el)});};document.addEventListener('click',handler,true);globalThis.__hcRecorder={q,stop:()=>document.removeEventListener('click',handler,true)};return true;})()`;
const RECORD_DRAIN=`(()=>globalThis.__hcRecorder?globalThis.__hcRecorder.q.splice(0):[])()`;
const RECORD_STOP=`(()=>{globalThis.__hcRecorder?.stop();delete globalThis.__hcRecorder;return true;})()`;
const SCROLL=`({x:scrollX/Math.max(1,document.documentElement.scrollWidth-innerWidth),y:scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)})`;
function scrollToRatio(x,y){return`scrollTo(${Math.max(0,Math.min(1,x||0))}*Math.max(0,document.documentElement.scrollWidth-innerWidth),${Math.max(0,Math.min(1,y||0))}*Math.max(0,document.documentElement.scrollHeight-innerHeight))`;}
function action(step){const selector=JSON.stringify(step.selector);return step.type==='click'?`(()=>{const el=document.querySelector(${selector});if(!el)throw Error('Elemento não encontrado');el.click();return true;})()`:`(()=>{const el=document.querySelector(${selector});return !!el&&String(el.textContent||'').includes(${JSON.stringify(step.expected)});})()`;}
module.exports={AUDIT,RECORD_START,RECORD_DRAIN,RECORD_STOP,SCROLL,scrollToRatio,action};
