'use strict';
const ALLOWED_TYPES=new Set(['media','geolocation','notifications']);
function cleanOrigin(value){try{const u=new URL(String(value||''));return u.protocol==='https:'?u.origin:'';}catch{return'';}}
function permissionKey(permission,details={}){const kind=String(permission||'');if(!ALLOWED_TYPES.has(kind))return'';if(kind!=='media')return kind;const requested=[],mediaTypes=Array.isArray(details.mediaTypes)?details.mediaTypes:details.mediaType?[details.mediaType]:[];if(mediaTypes.includes('audio'))requested.push('audio');if(mediaTypes.includes('video'))requested.push('video');return `media:${requested.length?requested.sort().join('+'):'unknown'}`;}
function normalizePermissionStore(raw){const decisions={};if(raw&&typeof raw.decisions==='object')for(const [key,value] of Object.entries(raw.decisions)){if(typeof key!=='string'||key.length>600||!['allow','block'].includes(value))continue;const split=key.lastIndexOf('|');if(split<1)continue;const origin=cleanOrigin(key.slice(0,split)),permission=key.slice(split+1);if(!origin||!permission)continue;decisions[`${origin}|${permission}`]=value;}return{version:1,decisions};}
function decisionId(origin,permission,details={}){const o=cleanOrigin(origin),p=permissionKey(permission,details);return o&&p?`${o}|${p}`:'';}
function getDecision(store,origin,permission,details={}){const id=decisionId(origin,permission,details);return id?normalizePermissionStore(store).decisions[id]||'':'';}
function setDecision(store,origin,permission,details={},decision=''){const next=normalizePermissionStore(store),id=decisionId(origin,permission,details);if(!id)return next;if(['allow','block'].includes(decision))next.decisions[id]=decision;else delete next.decisions[id];return next;}
function clearOrigin(store,origin){const next=normalizePermissionStore(store),o=cleanOrigin(origin);if(!o)return next;for(const key of Object.keys(next.decisions))if(key.startsWith(`${o}|`))delete next.decisions[key];return next;}
function permissionLabel(permission,details={}){const key=permissionKey(permission,details);if(key==='geolocation')return'sua localização';if(key==='notifications')return'enviar notificações';if(key==='media:audio')return'seu microfone';if(key==='media:video')return'sua câmera';if(key==='media:audio+video')return'sua câmera e seu microfone';return'este recurso protegido';}
module.exports=Object.freeze({ALLOWED_TYPES,cleanOrigin,permissionKey,normalizePermissionStore,decisionId,getDecision,setDecision,clearOrigin,permissionLabel});
